# Generated by Django 4.1.5 on 2023-05-01 16:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='occupant',
            field=models.ManyToManyField(blank=True, related_name='rent', to=settings.AUTH_USER_MODEL),
        ),
    ]
