# Generated by Django 4.1.5 on 2023-05-03 04:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0002_alter_rent_occupant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rent',
            name='occupant',
            field=models.ManyToManyField(blank=True, related_name='waiting_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rent',
            name='price',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='rent',
            name='quota',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
